### ISSUE TITLE
Panic running version1.4.0 and newer

### ISSUE THREAD

**Issue by betoredhat** [redhat-certification/chart-verifier#224]
Panic on version 1.4.1

```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
```

```
 podman info
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 80
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: jumphost.dfwt5g.lab
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1004
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1004
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 15542751232
  memTotal: 540411604992
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1004/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 1719730176
  swapTotal: 4294963200
  uptime: 4424h 52m 9.48s (Approximately 184.33 days)
registries:
  registry.dfwt5g.lab:4443:
    Blocked: false
    Insecure: true
    Location: registry.dfwt5g.lab:4443
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.dfwt5g.lab:4443
  registry.dfwt5g.lab:5000:
    Blocked: false
    Insecure: true
    Location: registry.dfwt5g.lab:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: registry.dfwt5g.lab:5000
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
  - quay.io
  - registry.dfwt5g.lab:5000
store:
  configFile: /home/dciteam/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-1.module+el8.5.0+12582+56d94c81.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/dciteam/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 338
  runRoot: /run/user/1004/containers
  volumePath: /home/dciteam/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1632213702
  BuiltTime: Tue Sep 21 03:41:42 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1
```
This is the panic generated:
```
$ podman run --rm  quay.io/redhat-certification/chart-verifier verify https://github.com/redhat-certification/chart-verifier/raw/main/pkg/chartverifier/checks/chart-0.1.0-v3.valid.tgz
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:erifier/checks/chart-0.1.0-v3.valid.tgz 
github.com/redhat-certification/chart-verifier/pkg/chartverifier/profiles.New(0xc00029a000)
	/tmp/src/pkg/chartverifier/profiles/profile.go:99 +0x3ec
github.com/redhat-certification/chart-verifier/cmd.buildChecks(0xc00003b740, 0x37de8a0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/tmp/src/cmd/verify.go:83 +0x46
github.com/redhat-certification/chart-verifier/cmd.NewVerifyCmd.func1(0xc0008d1400, {0xc00085f3c0, 0x1, 0x1})
	/tmp/src/cmd/verify.go:130 +0x297
github.com/spf13/cobra.(*Command).execute(0xc0008d1400, {0xc00085f320, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x36ba580)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/redhat-certification/chart-verifier/cmd.Execute()
	/tmp/src/cmd/root.go:39 +0x25
main.main()
	/tmp/src/main.go:21 +0x17
```

**Comment by bczoma** [comment]
Run into the same issue using Podman and also with the chart-verifier binary option from the release page (tried 1.4.1 only)

Interestingly, same command using Docker seemed to work for me (tried1.4.1) .

```
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1059-gcp
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 29.39GiB
 Name: openshift4x-test
 ID: YB2X:MGRK:EFMX:F25G:HXVH:Z63C:EW67:OY3Z:ELH6:TR7J:NR5V:D2WU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by mmulholla** [comment]
With the binary did you move the chart-verifier in the unzip before running it?

**Comment by bczoma** [comment]
@mmulholla , for the binary I followed https://github.com/redhat-certification/chart-verifier/blob/main/docs/helm-chart-checks.md#using-the-chart-verifier-binary-for-helm-chart-checks-linux-only - I simply did the unzip step as in the description, didn't move any files

**Comment by mmulholla** [comment]
> @mmulholla , for the binary I followed https://github.com/redhat-certification/chart-verifier/blob/main/docs/helm-chart-checks.md#using-the-chart-verifier-binary-for-helm-chart-checks-linux-only - I simply did the unzip step as in the description, didn't move any files

@bczoma Thanks, have figured the issue and working on a fix. Also, for info, the "main" image should now work for podman.

**Comment by bczoma** [comment]
Awesome, thanks @mmulholla !

**Comment by bczoma** [comment]
I can confirm that version 1.5.0 works for me now.
