### ISSUE TITLE
Chart-verified gives error generating chart report

### ISSUE THREAD

**Issue by atiwary91** [redhat-certification/chart-verifier#230]
Here is the PR for more info: https://github.com/openshift-helm-charts/charts/runs/4639797277?check_suite_focus=true

[Snip of error]

```
ow using project "charts-385" on server "https://api.appsvc-cert.lou4.p1.openshiftapps.com:6443".

charts-385/api-appsvc-cert-lou4-p1-openshiftapps-com:6443/system:serviceaccount:charts-385:charts-385
current-context: charts-385/api-appsvc-cert-lou4-p1-openshiftapps-com:6443/system:serviceaccount:charts-385:charts-385
[INFO] Get modified charts. ../pr
[INFO] Verify user. prajyotNarulkar925, partners, ibm-edge, nodered-chart
[INFO] Check owners file against directory structure. partners, ibm-edge, nodered-chart
[INFO] Generate verify report. ibm-edge, nodered-chart, 0.0.1
[INFO] report:
 Error: Chart.yaml file is missing
Usage:
  chart-verifier verify <chart-uri> [flags]

[INFO] Report does not exist:  charts/partners/ibm-edge/nodered-chart/0.0.1/report.yaml
[INFO] Check chart has same name and version as directory structure. ibm-edge, nodered-chart, 0.0.1
Call docker using imcge: quay.io/redhat-certification/chart-verifier:latest, docker command: report metadata /charts/report.yaml, report directory: /home/runner/work/charts/charts/pr-branch
Traceback (most recent call last):
  File "/home/runner/work/charts/charts/pr-branch/../ve1/bin/chart-pr-review", line 33, in <module>
    sys.exit(load_entry_point('rh-chart-repo-manager==0.1.0', 'console_scripts', 'chart-pr-review')())
  File "/home/runner/work/charts/charts/ve1/lib/python3.9/site-packages/rh_chart_repo_manager-0.1.0-py3.9.egg/chartprreview/chartprreview.py", line 372, in main
  File "/home/runner/work/charts/charts/ve1/lib/python3.9/site-packages/rh_chart_repo_manager-0.1.0-py3.9.egg/chartprreview/chartprreview.py", line 191, in match_name_and_version
  File "/home/runner/work/charts/charts/ve1/lib/python3.9/site-packages/rh_chart_repo_manager-0.1.0-py3.9.egg/report/report_info.py", line 76, in get_report_chart
  File "/home/runner/work/charts/charts/ve1/lib/python3.9/site-packages/rh_chart_repo_manager-0.1.0-py3.9.egg/report/report_info.py", line 31, in _get_report_info
  File "/home/runner/work/charts/charts/ve1/lib/python3.9/site-packages/docker/models/containers.py", line 840, in run
    raise ContainerError(
docker.errors.ContainerError: Command 'report metadata /charts/report.yaml' in image ''quay.io/redhat-certification/chart-verifier:latest' returned non-zero exit status 1: b''
```

**Comment by komish** [comment]
Unfortunately, the log output linked here does not exist anymore. Given the age of this issue, I'll close it out as stale. If this happens again, please don't hesitate to open a new issue with a fresh result link.
